language: generic

sudo: required

addons:
  apt:
    packages:
      - travis
      - python-pip

install:
  - openssl aes-256-cbc -K $encrypted_6bd89bcc047c_key -iv $encrypted_6bd89bcc047c_iv -in swarm.pem.enc -out $HOME/.ssh/swarm.pem -d
  - chmod 400 $HOME/.ssh/swarm.pem
  - echo $ENV
  - echo $HOME
  - sudo pip install awscli
  - aws configure set aws_access_key_id       $TF_VAR_AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key   $TF_VAR_AWS_SECRET_ACCESS_KEY
  - wget https://releases.hashicorp.com/terraform/0.10.7/terraform_0.10.7_linux_amd64.zip -O terraform.zip
  - sudo unzip terraform.zip -d /usr/local/bin/

script:
  bash ./terraform/destroy_apply.sh
